[workspace]
members = [
    "crates/analysis",
    "crates/api",
    "crates/build",
    "crates/cli",
    "crates/data",
    "crates/fingerprint",
    "crates/recorder"
]
default-members = [
    "crates/cli"
]
