[package]
name = "sg-history"
version = "0.1.0"
authors = ["Frank Denis <fdenis@fastly.com>"]
edition = "2018"

[dependencies]
mvdb = "0.3.0"
rouille = "3.0.0"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
