[package]
name = "sightglass-recorder"
version = "0.1.0"
description = "A measurement tool for compiling and running a single Wasm benchmark"
authors = ["Andrew Brown <andrew.brown@intel.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
cfg-if = "1.0"
libloading = "0.6"
log = "0.4"
perfcnt = "0.6"
precision = "0.1"
serde = { version = "1.0", features = ["derive"] }
sightglass-artifact = { path = "../artifact" }
thiserror = "1.0"

[dev-dependencies]
pretty_env_logger = "0.4"
wat = "1.0"
