name: native

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Build_Native_X86-64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
    - name: Rebuild benchmarks docker
      run: benchmarks/build-all-native.sh --run
