name: sightglass-result-server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: crates/result-server

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t sightglass-result-server:latest .
